# Change the command string to ^A, like Screen.
set -g prefix C-a
unbind-key C-b
#bind-key C-a send-prefix

# Turn off the clock.
set -g status-right ''

# Set "previous window" to command+backspace
unbind-key -T prefix p
bind-key -T prefix BSpace previous-window

# Set "next window" to command+spacebar
unbind-key -T prefix n
bind-key -T prefix Space next-window

# Kill the current window
unbind-key -T prefix &
unbind-key -T prefix k
bind-key -T prefix k kill-window

# This is probably a bad idea, but turn on mouse support.
set -g mouse on

# Screen-like "tap the command key twice to flip windows."
bind-key C-a last-window

