# Change the command string to ^A, like Screen.
set -g prefix C-a
unbind-key C-b
#bind-key C-a send-prefix

# Turn off the clock.
set -g status-right ''

# Turn off the session name.
set -g status-left ''

# Set "previous window" to command+backspace
unbind-key -T prefix p
bind-key -T prefix BSpace previous-window

# Set "next window" to command+spacebar
unbind-key -T prefix n
bind-key -T prefix Space next-window

# Kill the current window
unbind-key -T prefix &
unbind-key -T prefix k
bind-key -T prefix k kill-window

# This is probably a bad idea, but turn on mouse support.
# Up side: Highlighting text with the mouse automatically selects it.
# Down side: That's not necessarily what you want.
#set -g mouse on

# Screen-like "tap the command key twice to flip windows."
bind-key C-a last-window

# Define the default shell to open.
set -g default-shell /usr/bin/bash

# Make sure it's a login shell!
set -g default-command "/usr/bin/bash --login"

# Automatically renumber windows as they're closed and opened.
set -g renumber-windows on

# And now I'm playing around with theming.
# I do it this way because it's easier to reason about.
set -g status-style bg=black
set -g status-style fg=white

# Source: https://tmuxai.dev/tmux-custom-status-bar/
set -g window-status-current-style 'fg=#00ff00,bold'
set -g window-status-style 'fg=#999999'

