[General]
__userfile__=true
backlightIdleness=50
backlightIdlenessOnBatteryDischarging=true
disableIdlenessWhenFullscreen=false
enableBatteryWatcher=true
enableIdlenessBacklightWatcher=true
enableIdlenessWatcher=true
enableLidWatcher=true
iconType=1
idlenessACAction=-1
idlenessACTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessBatteryAction=4
idlenessBatteryTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessTime=@Variant(\0\0\0\xf\0\0\xea`)
powerLowAction=6
powerLowLevel=6
powerLowWarning=30
runCheckLevel=1
showIcon=true
