[General]
__userfile__=true

[fancymenu]
icon=/home/drwho/.icons/va_logo-64x64.png
ownIcon=true

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=45
lineCount=1
lockPanel=false
opacity=100
panelSize=45
plugins=fancymenu, taskbar, statusnotifier, tray, volume, worldclock, spacer
position=Bottom
reserve-space=true
screen-name=eDP-1
show-delay=0
visible-margin=true
width=100
width-percent=true

[spacer]
alignment=Left
type=spacer

[statusnotifier]
attentionPeriod=5
autoHideList=@Invalid()
hideList=@Invalid()
reverseOrder=false

[taskbar]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=IconText
buttonWidth=220
closeOnMiddleClick=false
excludedList=
groupingEnabled=false
iconByClass=false
raiseOnCurrentDesktop=false
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=false
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=true
ungroupedNextToExisting=false
wheelDeltaThreshold=300
wheelEventsAction=0

[volume]
alignment=Right
volumeAdjustStep=5

[worldclock]
alignment=Right
autoRotate=true
customFormat="'<b>'HH:mm:ss'</b><br/><font size=\"-2\">'ddd, d MMM yyyy'<br/>'TT'</font>'"
dateFormatType=custom
dateLongNames=false
datePadDay=false
datePosition=below
dateShowDoW=false
dateShowYear=false
defaultTimeZone=
formatType=custom-timeonly
showDate=false
showTimezone=false
showTooltip=false
showWeekNumber=true
timeAMPM=false
timePadHour=false
timeShowSeconds=false
timeZoneWheel=true
timeZones\size=0
timezoneFormatType=iana
timezonePosition=below
useAdvancedManualFormat=false
